In [3]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [5]:
my_list

[1, 2, 3]

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3,],[4,5,6],[7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((4))

array([1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.random.rand(5)   

array([0.01219874, 0.87515605, 0.2851369 , 0.1663054 , 0.09956088])

In [23]:
np.random.rand(5,5)   

array([[0.85116524, 0.88524526, 0.99129874, 0.12853496, 0.31160807],
       [0.94274614, 0.65115865, 0.15967908, 0.83690394, 0.72949033],
       [0.12756626, 0.32288251, 0.98164099, 0.73332912, 0.61993909],
       [0.736875  , 0.83114843, 0.57562801, 0.46780062, 0.47498823],
       [0.8179242 , 0.62056695, 0.60222473, 0.47736456, 0.58419556]])

In [24]:
np.random.randn(2)   

array([0.29634166, 0.34836959])

In [25]:
np.random.randn(4,4)   

array([[-0.82669237,  2.14128086,  0.03349436, -0.36693162],
       [-1.01087792,  0.46491357,  1.50556481,  0.86352557],
       [ 0.65504251,  1.11970863, -0.33235004,  0.27599048],
       [ 0.99499196,  1.40787391, -0.48647733, -1.28909805]])

In [26]:
np.random.randint(1,100,10)   

array([63, 53, 92, 67, 38, 96, 80, 58, 16, 97], dtype=int32)

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr =np.random.randint(0,50,10)   

In [30]:
ranarr

array([32,  1, 22, 34, 19, 24,  6, 39, 29, 43], dtype=int32)

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr

array([32,  1, 22, 34, 19, 24,  6, 39, 29, 43], dtype=int32)

In [34]:
ranarr.max()

np.int32(43)

In [35]:
ranarr.min()

np.int32(1)

In [36]:
ranarr

array([32,  1, 22, 34, 19, 24,  6, 39, 29, 43], dtype=int32)

In [37]:
ranarr.argmax()

np.int64(9)

In [38]:
ranarr.argmin()

np.int64(1)

In [39]:
arr.shape

(25,)

In [40]:
arr =arr.reshape(5,5)

In [41]:
arr.shape

(5, 5)

In [42]:
arr.dtype

dtype('int64')

In [43]:
import numpy
numpy.__version__


'2.3.5'